### ISSUE TITLE
macbook pro上使用删除键无效等问题

### ISSUE THREAD

**Issue by clark874** [BryceAndJuly/SiYuan_mindMap#1]
感谢作者的工作，补全了思源笔记对思维导图的支持空白。

macbook pro上使用挂件出现删除键无效，无法删除节点的情况。

同时删除设置了超链接的节点操作也很容易跳转。

使用检索后搜索窗口无法消除。

保存数据到文档没有反应。

请作者多多关注，再次感谢！

**Comment by BryceAndJuly** [comment]
社区相应文章链接：https://ld246.com/article/1649729865933

1、删除键无效
这个我是在windows 10上弄的，macbook上确实没试过。可是我现在手上只有windows的电脑，暂时没有调试环境。那先暂时搁置了，我后面有调试环境再优化一下；
2、删除设置了超链接的节点操作也很容易跳转
这个需要点边框后，再按删除键，暂时是这样的

3、使用检索后搜索窗口无法消除。
这个需要再次点击【检索】按钮来关闭搜索窗口；

4、保存数据到文档没有反应。
这个没有设置提示，但是本地试的时候，代码块会刷新一下；我用的1.9.7.1，代码块行号会闪一下；提示方面确实不明显；

不知道它在你那边的windows环境上使用可有出现问题？我在这边使用暂时是没有问题的。

**Comment by BryceAndJuly** [comment]
删除键无效的话，会不会是焦点问题，鼠标点一下之后再按呢？

**Comment by william2113** [comment]
Mac上面是 Fn 和删除键 同时按。
