### ISSUE TITLE
可否将挂件生成的 json 配置 放到 挂件自身的某个属性中

### ISSUE THREAD

**Issue by langyamu** [BryceAndJuly/SiYuan_mindMap#2]
主要是移动问题，将json配置放到 挂件自己的属性中 移动挂件的时候 思源会把配置一并也带过去

**Comment by BryceAndJuly** [comment]
那个JSON不只是配置，数据也在里面。要移动的话，直接把代码块复制过去就行了。然后在代码块上方插入导图挂件，挂件就会自动读取底部相邻代码块中的数据来生成导图了。

底部挂个代码块确实不优雅，但暂时没有更好的想法。如果只是移动导图的话，直接复制代码块就行，不用管上面那个导图。

**Comment by BryceAndJuly** [comment]
把数据写到属性的话，我先试试看好不好用。

**Comment by BryceAndJuly** [comment]
这个不太行，我把挂件复制过去的时候，它把我设置的四个属性全清空了。不管怎样，感谢提议。

**Comment by langyamu** [comment]
额 页内移动 挂件属性不会丢失，复制这 应该是思源的问题了

**Comment by BryceAndJuly** [comment]
哦，页内移动啊，页内拖拽那种吗？刚刚理解错了，以为是直接复制导图，然后粘贴到别处。其实如果复制的方式能不丢失属性值的话，数据写到属性里是挺好的，一个整体，不用拖着个数据块，而且移动、复制到别处也方便。

这个可以找时间提到社区里，等解决挂件复制后粘贴的块丢失属性值的问题后（我还没更新到最新版，不确定是不是已经解决了），直接把数据写属性里，然后随便移动、复制、粘贴都带着数据，状态还不会丢失，就很nice。

**Comment by BryceAndJuly** [comment]
社区帖子链接：[https://ld246.com/article/1651156033109](https://ld246.com/article/1651156033109)
请关注帖子中第三个版本的压缩包，截图如下：
![导图2](https://user-images.githubusercontent.com/58081876/167558261-8007454c-a307-417c-8203-d26fcd39dc86.png)

**Comment by BryceAndJuly** [comment]
第三个版本也是我自己在用的，然后我笔记版本更新到2.0.5之后，在main.js那里修改的跟2.0.2的稍有不同。
版本：2.0.5
修改main.js

搜索

```js
r=n(1472);
```

替换成

```js
r=n(1472);window._a=a;
```

搜索

```js
N=n(8528);
```

替换成

```js
N=n(8528);window._M=P;window._o=o;
```

还是希望官方能内置基本导图功能吧，挂件始终不太方便，不同版本那个方法名都可能在变，每次改好麻烦。
