### ISSUE TITLE
超链接悬浮预览

### ISSUE THREAD

**Issue by william2113** [BryceAndJuly/SiYuan_mindMap#3]
感谢大佬。另外，节点插入块超链接之后，鼠标放在节点上，能实现悬浮预览吗？像是思源笔记那种悬浮预览。

**Comment by BryceAndJuly** [comment]
这个没试过，悬浮预览相关的逻辑应该是在 SiYuan\resources\stage\build\app\main.js里属性1619对应的那个函数中，你可以先看看，我之后有时间再折腾看看吧，暂时怕是没时间整了。

**Comment by BryceAndJuly** [comment]
我刚刚看了一下，这个还好，不难弄，就是要稍微修改一下`SiYuan\resources\stage\build\app\main.js`。
你用vscode打开这个mian.js，格式化一下，搜索1619，会找到一个函数，在   r = n(1472);  往后一点添上  window._a = a; 将方法暴露到全局中，如下：

```js
  1619: function (e, t, n) {
        "use strict";
        var i =
          (this && this.__awaiter) ||
          function (e, t, n, i) {
            return new (n || (n = Promise))(function (a, s) {
              function o(e) {
                try {
                  l(i.next(e));
                } catch (e) {
                  s(e);
                }
              }
              function r(e) {
                try {
                  l(i.throw(e));
                } catch (e) {
                  s(e);
                }
              }
              function l(e) {
                var t;
                e.done
                  ? a(e.value)
                  : ((t = e.value),
                    t instanceof n
                      ? t
                      : new n(function (e) {
                          e(t);
                        })).then(o, r);
              }
              l((i = i.apply(e, t || [])).next());
            });
          };
        Object.defineProperty(t, "__esModule", { value: !0 }),
          (t.initBlockPopover = void 0);
        const a = n(3781),
          s = n(6902),
          o = n(3383),
          r = n(1472);
        window._a = a;
```

然后在<br />工作空间\data\widgets\思维导图\static\jsmind.shell.js这个文件最后那里加上：

```js
setTimeout(function () {
  document.addEventListener(
    "mouseover",
    function (e) {
      if (e.target.tagName === "A") {
        let l = e.target.getAttribute("href");
        if (l.startsWith("siyuan://blocks")) {
          let id = l.split("://blocks/")[1];
          let Arr= []
          Arr.push(id)
          setTimeout(()=>{
            window.parent.siyuan.blockPanels.push(
                new window.parent._a.BlockPanel({ targetElement: e.target, nodeIds: Arr })
              );
          },500)
        
        }
      }
    },
    false
  );
}, 2000);

```

**Comment by BryceAndJuly** [comment]
因为这个要改main.js，所以单单搞思维导图的更新没用，还是自己手动改一下。可惜这里不能传视频，我试了是可以的，你自己试试吧。

**Comment by william2113** [comment]
感谢你的热情回复。但是，可能要让你失望了。🤦‍♂️ 。我是纯粹的小白，用的 Mac，笨的找不到你说的文件。一点也不懂编程。还是要感谢你开发的挂件。谢谢。🫰🫶

**Comment by william2113** [comment]
通过一番搜索，你提到的文件夹都找到了。 另外，将方法暴露到全局中 请问怎样暴露。😄

**Comment by BryceAndJuly** [comment]
问题不大，稍后有空的时候我整理一下发到链滴社区，那里可以发视频；我本地在用的那个思维导图挂件跟集市里的稍有不同，做了一些修改：
1、样式上，改成了黑夜模式，乍一看好看了一点，原来的蓝白配色有点难看；
2、原来的超链接，点击之后跳转的很慢，我改成了引用块跳转的形式，现在基本是点了就秒开；
3、超链接悬浮预览，我设置的是，按住Alt后悬浮才会显示预览，不然容易误操作，老是弹出预览；
4、插入超链接的时候，除了可以使用【复制块超链接】的方式，还可以使用【复制该块为引用块】的形式。

除了挂件做了点更新，到时候还需要在main.js中添加3行代码。这个等整理好再说吧，我在本地用着暂时没出问题；

**Comment by william2113** [comment]
大佬。用VScode打开后，搜索不到1619，也搜索不到 r = n(1472) 🥹

**Comment by BryceAndJuly** [comment]
打开main.js

搜索

```js
r=n(1472);
```

在后面添上

```js
window._a=a;
```


搜索

```js
$=n(8528);
```

在后面添上

```js
window._M=M;window._o=o;
```

**Comment by BryceAndJuly** [comment]
别格式化了，直接复制这个去搜索吧；弄之前先备份好main.js，别搞坏了就不好了

**Comment by BryceAndJuly** [comment]
哥们，先别弄了，等我整理好发个帖子，你再看吧，别把笔记整崩了。

**Comment by william2113** [comment]
好的，等待大佬的教程

**Comment by BryceAndJuly** [comment]
https://ld246.com/article/1651156033109

**Comment by william2113** [comment]
<img width="1166" alt="截屏2022-04-29 07 50 18" src="https://user-images.githubusercontent.com/65440664/165865595-553c27e0-4e8b-4975-85af-c061c72825ec.png">

**Comment by william2113** [comment]
十分感谢。但是，打开包内容之后，没有main.js 只有一个main.33c495c7b1bf110307fb 里面搜索不到 r=n(1472);  也搜索不到 $=n(8528); 
使用的是Mac平台 Visual Studio Code，版本: 1.66.2
<img width="1166" alt="截屏2022-04-29 07 50 18" src="https://user-images.githubusercontent.com/65440664/165866253-8f5c8c9f-2f94-4a8c-ba9d-5a227b636d13.png">
找到的 js 文件压缩如下：
[main.33c495c7b1bf110307fb.zip](https://github.com/BryceAndJuly/SiYuan_mindMap/files/8587347/main.33c495c7b1bf110307fb.zip)

**Comment by BryceAndJuly** [comment]
你的文件还真跟我的不一样，我的是windows平台的，代码可能有点差异吧。之前没注意这个问题。
![对比](https://user-images.githubusercontent.com/58081876/165867376-9af859ef-fbd1-41a9-8482-71761729c5c3.png)

**Comment by BryceAndJuly** [comment]
要用的方法应该都在，可能编号不一样，我 到时候帮你看看你发过来的那段代码。

**Comment by BryceAndJuly** [comment]
我的文件

```js
r=n(1472);
```

你的文件

```js
r=n(9295);
```



我的文件

```js
$=n(8528);
```

你的文件

```js
$=n(3532);
```

**Comment by BryceAndJuly** [comment]
溜了溜了

**Comment by william2113** [comment]
十分感谢大佬的耐心讲解🙏，现在已经搞好了。
