### ISSUE TITLE
后面会添加一种向右的结构吗？

### ISSUE THREAD

**Issue by winter60** [BryceAndJuly/SiYuan_mindMap#4]
目前好像是左右分开的这种结构，希望后续可以添加向右的结构
![image](https://user-images.githubusercontent.com/23653326/175765633-5f840089-e483-455f-808e-ff6a4db79ab8.png)

**Comment by BryceAndJuly** [comment]
哦，这个不难，你打开挂件那个文件夹里的 static/jsmind.js，搜一下：
`mode:"full"`
改成
`mode:"side"`
就可以了
