### ISSUE TITLE
小建议：编辑状态按enter的效果

### ISSUE THREAD

**Issue by winter60** [BryceAndJuly/SiYuan_mindMap#5]
目前在编辑状态按enter会直接创建兄弟节点，这在对节点加超链接时有点不友好。
建议编辑状态按enter则切换到选中节点的状态，选中状态按enter再创建可能会比较好。
http://hizzgdev.github.io/jsmind/ 官网demo好像能实现这个效果

打扰了~

**Comment by BryceAndJuly** [comment]
应该是之前觉得按太多次Enter键挺麻烦，所以改成连续输入的形式了，回头我看看改哪里了。

**Comment by BryceAndJuly** [comment]
要不简单处理一下，在生成链接之后让它结束编辑状态吧，加一句`v.edit_node_end();`就行；
在static/jsmind.js，搜索
`else{e.target.value=`<a href="${nodeHref}"target="_blank">${nodeText}</a>`}`
改成
`else{e.target.value=`<a href="${nodeHref}"target="_blank">${nodeText}</a>`}v.edit_node_end();`

**Comment by BryceAndJuly** [comment]
要不简单处理一下，在生成链接之后让它结束编辑状态吧，加一句 v.edit_node_end(); 就行；
在static/jsmind.js，搜索
else{e.target.value=`<a href="${nodeHref}"target="_blank">${nodeText}</a>`}
改成：
else{e.target.value=`<a href="${nodeHref}"target="_blank">${nodeText}</a>`}v.edit_node_end();

**Comment by BryceAndJuly** [comment]
要不简单处理一下，在生成链接之后让它结束编辑状态吧，加一句`v.edit_node_end();`就行；
在static/jsmind.js，搜索

```js
else{e.target.value=`<a href="${nodeHref}"target="_blank">${nodeText}</a>`}
```

改成

```js
else{e.target.value=`<a href="${nodeHref}"target="_blank">${nodeText}</a>`}v.edit_node_end();
```

**Comment by BryceAndJuly** [comment]
这样平时也能连续输入节点，插入链接的时候也不用按Enter了。

**Comment by winter60** [comment]
> 这样平时也能连续输入节点，插入链接的时候也不用按Enter了。

可以了，非常感谢和蔼可亲的作者~👍
